# -*- coding: utf-8 -*-
"""HW5-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sjRiNbDcyI2lf7H-J-mhaStcBtsQPCa3
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

col_names = ['Age of the patient','Spectacle prescription','Astigmatic','Tear production rate','Class']
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/lenses/lenses.data", header=None, names=col_names,sep='\s+', engine='python')
data.head()

feature_cols = ['Age of the patient','Spectacle prescription','Astigmatic','Tear production rate']
X = data[feature_cols] 
y = data.Class

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

clf = DecisionTreeClassifier()

clf = clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('lenses.png')
Image(graph.create_png())

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

clf = DecisionTreeClassifier(max_depth=4)
clf = clf.fit(X_train,y_train)

plt.figure(figsize=(25,10))
a = plot_tree(clf, 
              feature_names = feature_cols, 
              filled=True, 
              rounded=True, 
              fontsize=14)